/*
#*****************************************************#
#Created:10/30/2015                                   #
#Author:  Sudheer Kondla, sudheer.kondla@gmail.com           #
#*****************************************************#
*/

SET DEFINE OFF
alter session set NLS_DATE_FORMAT='MM/DD/YYYY HH24:MI:SS';
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (1.0,1.0,1.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (2.0,1.0,2.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (3.0,1.0,3.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (4.0,1.0,4.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (5.0,1.0,5.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (6.0,1.0,6.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (7.0,1.0,7.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (8.0,1.0,8.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (9.0,1.0,9.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (10.0,1.0,10.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (11.0,1.0,11.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (12.0,1.0,12.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (13.0,1.0,13.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (14.0,1.0,14.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (15.0,1.0,15.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (16.0,1.0,16.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (17.0,1.0,17.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (18.0,1.0,18.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (19.0,1.0,19.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (20.0,1.0,20.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (21.0,1.0,21.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (22.0,1.0,22.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (23.0,1.0,23.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (24.0,1.0,24.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (25.0,1.0,25.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (26.0,1.0,26.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (27.0,1.0,27.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (28.0,1.0,28.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (29.0,4.0,1.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (30.0,4.0,2.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (31.0,4.0,3.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (32.0,4.0,4.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (33.0,4.0,5.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (34.0,4.0,6.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (35.0,4.0,7.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (36.0,4.0,8.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (37.0,4.0,9.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (38.0,4.0,10.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (39.0,4.0,11.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (40.0,4.0,12.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (41.0,4.0,13.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (42.0,4.0,14.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (43.0,4.0,15.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (44.0,4.0,16.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (45.0,4.0,17.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (46.0,4.0,18.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (47.0,4.0,19.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (48.0,4.0,20.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (49.0,4.0,21.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (50.0,4.0,22.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (51.0,4.0,23.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (52.0,4.0,24.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (53.0,4.0,25.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (54.0,4.0,26.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (55.0,4.0,27.0,to_date('10/26/2015'),'Tom McKincey');
INSERT INTO SMARTACCT.ROLE_RESOURCE (ROLE_RESOURCE_ID, ROLE_ID, RESOURCE_ID, CREATED_ON, CREATED_BY) VALUES (56.0,4.0,28.0,to_date('10/26/2015'),'Tom McKincey');
Commit;
